# nothing here
CONFIG_KERNEL_BIN_NAME="ipc"
CONFIG_NO_OPTIMIZATIONS=y
CONFIG_DEBUG=y
CONFIG_USE_DT_CODE_PARTITION=y

#off banner massage
CONFIG_BOOT_BANNER=n

CONFIG_USE_DT_CODE_PARTITION=y
CONFIG_REBOOT=y
CONFIG_RTC=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_SHELL=y
CONFIG_DCACHE=n
CONFIG_DATE_SHELL=n

#uart 설정
CONFIG_UART_ASYNC_API=y
CONFIG_UART_INTERRUPT_DRIVEN=y